connection_error = "通信エラー"
class ConnectionError_Body:
    Token_Fail = "ERR_AM_IDTOKEN_FAIL"
    Timeout = "FBR_ERR_TIMEOUT"
data_update = "データ更新"
date_update = "日付変更"
data_download = "データダウンロード"
init_error = "初期化エラー"
receipt_completed = "受取完了"
rate_reward = "レート報酬"
exchange_confirmation = "交換確"
work_start_confirmation = "仕事開始確"
expenditure = "活動費"
destroying_production_data = "プロデュースデータの破棄"
confirm = "確認"
class DispatchWorkError:
    other_selectable_idols = "他に選択可能な好調状態のアイドルがいます二のまま決へ進れでよろしいです力？"