name: Release

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发，如 v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: false
      prerelease:
        description: "prerelease"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

permissions:
  contents: write  # 允许创建 release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          lfs: true
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web-ui/package.json

      - name: Add MinGW to PATH
        run: echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Use ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.dev.txt

      - name: Export Model
        run: |
          python ./devtools/model_export.py

      - name: Get Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: out/app.build
          key: ${{ runner.os }}-nuitka-build-${{ hashFiles('**/build_app.py') }}
          restore-keys: |
            ${{ runner.os }}-nuitka-build-

      - name: Build app
        run: |
          python build_app.py
        env:
          CFLAGS: "/Zm200"
          GITHUB_ACTIONS: "True"

      - name: Compress Output
        run: |
          $source = "${{ github.workspace }}\out\app.dist"
          $zipFile = "${{ github.workspace }}\release.zip"
          Compress-Archive -Path "$source\*" -DestinationPath "$zipFile" -Force

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}
          name: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
